# Generated by Django 4.2.30 on 2026-08-05 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('unidade_medida', models.CharField(help_text='Ex: Toneladas, R$/TKU', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='TerminalLogistico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150)),
                ('tipo', models.CharField(choices=[('porto_seco', 'Porto Seco'), ('patio', 'Pátio Ferroviário'), ('transbordo', 'Área de Transbordo'), ('outro', 'Outro')], max_length=20)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('capacidade', models.CharField(blank=True, help_text='Ex: 500 TEUs/dia', max_length=150, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrechoFerroviario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Ex: Uruguaiana - Cacequi', max_length=150)),
                ('origem', models.CharField(max_length=100)),
                ('destino', models.CharField(max_length=100)),
                ('distancia_km', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('inativo', 'Inativo/Sucateado'), ('manutencao', 'Em Manutenção')], default='ativo', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='RegistroDado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=12)),
                ('data_registro', models.DateField()),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registros', to='logistica.indicador')),
                ('terminal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.terminallogistico')),
                ('trecho', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='logistica.trechoferroviario')),
            ],
        ),
    ]
